### ISSUE TITLE
customViewportCorrectionVariable is not defined

### ISSUE THREAD

**Issue by momtboy** [Miofly/vite-plugin-html-template-mpa#1]
`[vite-plugin-html-template-mpa] Could not load D:/workspace/code/webspa/ShopDancingAdmin/index.html: customViewportCorrectionVariable is not defined
error during build:
ReferenceError: Could not load D:/workspace/code/webspa/ShopDancingAdmin/index.html: customViewportCorrectionVariable is not defined
    at eval (lodash.templateSources[0]:13:10)
    at getHtmlContent (D:\workspace\code\webspa\ShopDancingAdmin\node_modules\vite-plugin-html-template-mpa\dist\index.js:5574:10)
    at async file:///D:/workspace/code/webspa/ShopDancingAdmin/node_modules/rollup/dist/es/shared/rollup.js:22095:98
    at async Queue.work (file:///D:/workspace/code/webspa/ShopDancingAdmin/node_modules/rollup/dist/es/shared/rollup.js:22772:32)`

**Comment by Miofly** [comment]
> `[vite-plugin-html-template-mpa] Could not load D:/workspace/code/webspa/ShopDancingAdmin/index.html: customViewportCorrectionVariable is not defined error during build: ReferenceError: Could not load D:/workspace/code/webspa/ShopDancingAdmin/index.html: customViewportCorrectionVariable is not defined at eval (lodash.templateSources[0]:13:10) at getHtmlContent (D:\workspace\code\webspa\ShopDancingAdmin\node_modules\vite-plugin-html-template-mpa\dist\index.js:5574:10) at async file:///D:/workspace/code/webspa/ShopDancingAdmin/node_modules/rollup/dist/es/shared/rollup.js:22095:98 at async Queue.work (file:///D:/workspace/code/webspa/ShopDancingAdmin/node_modules/rollup/dist/es/shared/rollup.js:22772:32)`

是最新版本吗最新版本更新至 0.0.11，解决了一些 windows 上的问题

**Comment by Miofly** [comment]
> `[vite-plugin-html-template-mpa] Could not load D:/workspace/code/webspa/ShopDancingAdmin/index.html: customViewportCorrectionVariable is not defined error during build: ReferenceError: Could not load D:/workspace/code/webspa/ShopDancingAdmin/index.html: customViewportCorrectionVariable is not defined at eval (lodash.templateSources[0]:13:10) at getHtmlContent (D:\workspace\code\webspa\ShopDancingAdmin\node_modules\vite-plugin-html-template-mpa\dist\index.js:5574:10) at async file:///D:/workspace/code/webspa/ShopDancingAdmin/node_modules/rollup/dist/es/shared/rollup.js:22095:98 at async Queue.work (file:///D:/workspace/code/webspa/ShopDancingAdmin/node_modules/rollup/dist/es/shared/rollup.js:22772:32)`

还有问题吗？
