### ISSUE TITLE
mac m1 can't compile javascript

### ISSUE THREAD

**Issue by duyuxuan** [Miofly/vite-plugin-html-template-mpa#3]
The js folder can be successfully compiled on the windows computer.Unable to compile on mac m1

**Comment by Miofly** [comment]
> 

能提供一个最简单的测试demo吗

**Comment by Miofly** [comment]
> The js folder can be successfully compiled on the windows computer.Unable to compile on mac m1


能提供一个最简单的测试demo吗

**Comment by duyuxuan** [comment]
感谢回复，我通过邮件把测试用的demo发给您QQ邮箱了，请查收。

**Comment by Miofly** [comment]
> 感谢回复，我通过邮件把测试用的demo发给您QQ邮箱了，请查收。

就demo而言，news下那个index.html换个名称即可，不要用 index 开头，可以临时这样处理试试

**Comment by duyuxuan** [comment]
超级感谢，我试了一下确实是不要用 index 开头就可以诶，大概是为什么呢？

**Comment by Miofly** [comment]
> 超级感谢，我试了一下确实是不要用 index 开头就可以诶，大概是为什么呢？

与public/index.html在某些情况下会出现冲突，不使用index.html，事实上，很少有在此目录下加入index.html的情况，暂不处理

**Comment by duyuxuan** [comment]
嗯，再次感谢您帮忙解决问题
