### ISSUE TITLE
Please release the new version

### ISSUE THREAD

**Issue by woyehenni** [Miofly/vite-plugin-html-template-mpa#5]
https://www.npmjs.com/package/vite-plugin-html-template-mpa

The latest version is 0.0.19 which published a year ago.
It cannot run on vite: "4.5.0". 
I see that you have made modifications, so can you publish a new Release? Thank you.

```
webview/node_modules/vite-plugin-html-template-mpa/dist/index.js:5710
            hasUnocss: JSON.stringify(config.plugins).includes("unocss"),
                            ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Array'
    |     index 14 -> object with constructor 'Object'
    |     property 'api' -> object with constructor 'Object'
    |     ...
    |     property 'config' -> object with constructor 'Object'
    --- property 'plugins' closes the circle
    at JSON.stringify (<anonymous>)
```

**Comment by Miofly** [comment]
> https://www.npmjs.com/package/vite-plugin-html-template-mpa
> 
> The latest version is 0.0.19 which published a year ago. It cannot run on vite: "4.5.0". I see that you have made modifications, so can you publish a new Release? Thank you.
> 
> ```
> webview/node_modules/vite-plugin-html-template-mpa/dist/index.js:5710
>             hasUnocss: JSON.stringify(config.plugins).includes("unocss"),
>                             ^
> 
> TypeError: Converting circular structure to JSON
>     --> starting at object with constructor 'Array'
>     |     index 14 -> object with constructor 'Object'
>     |     property 'api' -> object with constructor 'Object'
>     |     ...
>     |     property 'config' -> object with constructor 'Object'
>     --- property 'plugins' closes the circle
>     at JSON.stringify (<anonymous>)
> ```

ok, In the next two days, I will make the following corrections to the functionality of this plugin to adapt to the situation of Vite > 4.0

**Comment by Miofly** [comment]
in vite-plugin-html-template-mpa 1.0.3 is settle and vite-plugin-multi-pages is 0.0.13
