### ISSUE TITLE
use this plugin  error  when router changed 

### ISSUE THREAD

**Issue by ashuicoder** [Miofly/vite-plugin-html-template-mpa#7]
[Vue warn]: There is already an app instance mounted on the host container.
 If you want to mount another app on the same host container, you need to unmount the previous app by calling `app.unmount()` first

**Comment by Miofly** [comment]
> [Vue warn]: There is already an app instance mounted on the host container. If you want to mount another app on the same host container, you need to unmount the previous app by calling `app.unmount()` first

Can you provide a demo for reproduction?
