### ISSUE TITLE
会处理掉page/page1/index.html 自己添加的一些dom和数据

### ISSUE THREAD

**Issue by cjh-store** [Miofly/vite-plugin-html-template-mpa#8]
![image](https://github.com/Miofly/vite-plugin-html-template-mpa/assets/88535245/bd05e61f-22e5-4039-8d53-9cf3ce0e7d0a)
<div>22222222</div>消失了

单独使用vite-plugin-multi-pages 不会

**Comment by Miofly** [comment]
> ![image](https://private-user-images.githubusercontent.com/88535245/330360684-bd05e61f-22e5-4039-8d53-9cf3ce0e7d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODUzNDcsIm5iZiI6MTcxNTY4NTA0NywicGF0aCI6Ii84ODUzNTI0NS8zMzAzNjA2ODQtYmQwNWU2MWYtMjJlNS00MDM5LThkNTMtOWNmM2NlMGU3ZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDExMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYmNkMmFjNmEyY2MxMzdkNjY2NTE4M2Y5ZjI2MTgxY2E0OGEzYTJlZjEyYTdiYmI5MjFjNDM1YWYzOTQ2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cLCI6FEEz2uQOSw_iyT6lSc3PjLkYSYqbP-754cxePU)
> 
> 22222222
> 消失了
> 单独使用vite-plugin-multi-pages 不会

你可以在 vite 配置中指定模版的位置，否则他将应用默认模版
```
   pages: {
        'test-twos': {
          urlParams: 'id=33',
          template: resolve(process.cwd(), 'src/views/test-two/index.html'),
        },
      },
```

**Comment by cjh-store** [comment]
> > ![image](https://private-user-images.githubusercontent.com/88535245/330360684-bd05e61f-22e5-4039-8d53-9cf3ce0e7d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODUzNDcsIm5iZiI6MTcxNTY4NTA0NywicGF0aCI6Ii84ODUzNTI0NS8zMzAzNjA2ODQtYmQwNWU2MWYtMjJlNS00MDM5LThkNTMtOWNmM2NlMGU3ZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDExMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYmNkMmFjNmEyY2MxMzdkNjY2NTE4M2Y5ZjI2MTgxY2E0OGEzYTJlZjEyYTdiYmI5MjFjNDM1YWYzOTQ2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cLCI6FEEz2uQOSw_iyT6lSc3PjLkYSYqbP-754cxePU)
> > 22222222
> > 消失了
> > 单独使用vite-plugin-multi-pages 不会
> 
> 你可以在 vite 配置中指定模版的位置，否则他将应用默认模版
> 
> ```
>    pages: {
>         'test-twos': {
>           urlParams: 'id=33',
>           template: resolve(process.cwd(), 'src/views/test-two/index.html'),
>         },
>       },
> ```

可行 感谢
