### ISSUE TITLE
moderate severity vulnerabilities

### ISSUE THREAD

**Issue by woyehenni** [Miofly/vite-plugin-html-template-mpa#9]
ejs version too low?

```
# npm audit report

ejs  <3.1.10
Severity: moderate
ejs lacks certain pollution protection - https://github.com/advisories/GHSA-ghr5-ch3p-vcr6
fix available via `npm audit fix --force`
Will install vite-plugin-html-template-mpa@0.0.19, which is a breaking change
node_modules/ejs
  vite-plugin-html-template-mpa  >=1.0.0
  Depends on vulnerable versions of ejs
  node_modules/vite-plugin-html-template-mpa

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by Miofly** [comment]
> ejs version too low?
> 
> ```
> # npm audit report
> 
> ejs  <3.1.10
> Severity: moderate
> ejs lacks certain pollution protection - https://github.com/advisories/GHSA-ghr5-ch3p-vcr6
> fix available via `npm audit fix --force`
> Will install vite-plugin-html-template-mpa@0.0.19, which is a breaking change
> node_modules/ejs
>   vite-plugin-html-template-mpa  >=1.0.0
>   Depends on vulnerable versions of ejs
>   node_modules/vite-plugin-html-template-mpa
> 
> 2 moderate severity vulnerabilities
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> ```

vite-plugin-html-template-mpa@1.0.12 is updated
